# Generated by Django 5.2.5 on 2025-08-30 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemonentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='pokemon',
        ),
    ]
